#############################################################################
# Makefile for building: BookKeeping
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  BookKeeping.pro
# Template: subdirs
# Command: C:\Qt\5.12.0\mingw73_64\bin\qmake.exe -o Makefile BookKeeping.pro -spec win32-g++
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.12.0\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.12.0\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.12.0\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-BookKeeping \
		sub-Book \
		sub-Currency


sub-BookKeeping-qmake_all:  FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++
	cd BookKeeping\ && $(MAKE) -f Makefile qmake_all
sub-BookKeeping: FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile
sub-BookKeeping-make_first: FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-BookKeeping-all: FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-BookKeeping-clean: FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-BookKeeping-distclean: FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-BookKeeping-install_subtargets: FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-BookKeeping-uninstall_subtargets: FORCE
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall
sub-Book-qmake_all:  FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++
	cd Book\ && $(MAKE) -f Makefile qmake_all
sub-Book: FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile
sub-Book-make_first: FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-Book-all: FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-Book-clean: FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-Book-distclean: FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-Book-install_subtargets: FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-Book-uninstall_subtargets: FORCE
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall
sub-Currency-qmake_all:  FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++
	cd Currency\ && $(MAKE) -f Makefile qmake_all
sub-Currency: FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile
sub-Currency-make_first: FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile 
sub-Currency-all: FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile all
sub-Currency-clean: FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile clean
sub-Currency-distclean: FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile distclean
sub-Currency-install_subtargets: FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile install
sub-Currency-uninstall_subtargets: FORCE
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile uninstall

Makefile: BookKeeping.pro ../../../../Qt/5.12.0/mingw73_64/mkspecs/win32-g++/qmake.conf ../../../../Qt/5.12.0/mingw73_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/qdevice.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/common/g++-base.conf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/common/angle.conf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/common/windows-vulkan.conf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/common/g++-win32.conf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/qconfig.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/win32-g++/qmake.conf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/precompile_header.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/win32/windows.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.12.0/mingw73_64/mkspecs/features/lex.prf \
		BookKeeping.pro
	$(QMAKE) -o Makefile BookKeeping.pro -spec win32-g++
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/qdevice.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/device_config.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/common/g++-base.conf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/common/angle.conf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/common/windows-vulkan.conf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/common/g++-win32.conf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/qconfig.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/win32-g++/qmake.conf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/spec_post.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/toolchain.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/win32/default_pre.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/default_post.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/precompile_header.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/qmake_use.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/win32/windows.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/yacc.prf:
../../../../Qt/5.12.0/mingw73_64/mkspecs/features/lex.prf:
BookKeeping.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile BookKeeping.pro -spec win32-g++

qmake_all: sub-BookKeeping-qmake_all sub-Book-qmake_all sub-Currency-qmake_all FORCE

make_first: sub-BookKeeping-make_first sub-Book-make_first sub-Currency-make_first  FORCE
all: sub-BookKeeping-all sub-Book-all sub-Currency-all  FORCE
clean: sub-BookKeeping-clean sub-Book-clean sub-Currency-clean  FORCE
distclean: sub-BookKeeping-distclean sub-Book-distclean sub-Currency-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-BookKeeping-install_subtargets sub-Book-install_subtargets sub-Currency-install_subtargets FORCE
uninstall_subtargets: sub-BookKeeping-uninstall_subtargets sub-Book-uninstall_subtargets sub-Currency-uninstall_subtargets FORCE

sub-BookKeeping-debug:
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile debug
sub-Book-debug:
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile debug
sub-Currency-debug:
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile debug
debug: sub-BookKeeping-debug sub-Book-debug sub-Currency-debug

sub-BookKeeping-release:
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile release
sub-Book-release:
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile release
sub-Currency-release:
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile release
release: sub-BookKeeping-release sub-Book-release sub-Currency-release

sub-BookKeeping-check:
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile check
sub-Book-check:
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile check
sub-Currency-check:
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile check
check: sub-BookKeeping-check sub-Book-check sub-Currency-check

sub-BookKeeping-benchmark:
	@if not exist BookKeeping\ mkdir BookKeeping\ & if not exist BookKeeping\ exit 1
	cd BookKeeping\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\BookKeeping\BookKeeping.pro -spec win32-g++ ) && $(MAKE) -f Makefile benchmark
sub-Book-benchmark:
	@if not exist Book\ mkdir Book\ & if not exist Book\ exit 1
	cd Book\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Book\Book.pro -spec win32-g++ ) && $(MAKE) -f Makefile benchmark
sub-Currency-benchmark:
	@if not exist Currency\ mkdir Currency\ & if not exist Currency\ exit 1
	cd Currency\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\cowto\GitHub\BookKeeping\Currency\Currency.pro -spec win32-g++ ) && $(MAKE) -f Makefile benchmark
benchmark: sub-BookKeeping-benchmark sub-Book-benchmark sub-Currency-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

