CREATE TABLE [currency_currency](
  [Date] TEXT PRIMARY KEY DESC NOT NULL, 
  [EUR] [DOUBLE PRECISION] NOT NULL, 
  [USD] [DOUBLE PRECISION] NOT NULL, 
  [CNY] [DOUBLE PRECISION] NOT NULL, 
  [GBP] [DOUBLE PRECISION] NOT NULL) WITHOUT ROWID;

CREATE TABLE "CurrencyTypes"([Name] TEXT PRIMARY KEY ASC) WITHOUT ROWID;\

INSERT INTO "CurrencyTypes"
    (Name)
VALUES
    ("CNY"),
    ("EUR"),
    ("GBP"),
    ("USD");
